Revert "chore: bump to Node 26"
Netlify error:

```
Error: Cannot find module '/opt/buildhome/.cache/node/corepack/v1/pnpm/12.8.1/bin/pnpm.cjs'
```

This reverts commit 296ab398e4376468be5687559987774aa5712940.